AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  scriptsBucket:
    Type: String
  rawBucket:
    Type: String
  stagingBucket:
    Type: String
  transformedBucket:
    Type: String
  mlBucket:
    Type: String
  lambdaRaw2stagingVersion:
    Type: String
  kmsKeyForDEArn:
    Type: String
  kmsKeyForMLArn:
    Type: String


Resources:
  GlueJobStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${scriptsBucket}/cloudformation/glueJob.yml"
      Parameters:
        scriptsBucket: !Ref scriptsBucket
        kmsKeyForDEArn: !Ref kmsKeyForDEArn
        kmsKeyForMLArn: !Ref kmsKeyForMLArn

  LambdaStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${scriptsBucket}/cloudformation/lambda.yml"
      Parameters:
        scriptsBucket: !Ref scriptsBucket
        rawBucket: !Ref rawBucket
        stagingBucket: !Ref stagingBucket
        lambdaRaw2stagingVersion: !Ref lambdaRaw2stagingVersion
        kmsKeyForDEArn: !Ref kmsKeyForDEArn

  GlueCatalogStagingStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${scriptsBucket}/cloudformation/glueCatalogStaging.yml"
      Parameters:
        stagingBucket: !Ref stagingBucket

  GlueCatalogTransformedStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${scriptsBucket}/cloudformation/glueCatalogTransformed.yml"
      Parameters:
        transformedBucket: !Ref transformedBucket

  GlueCatalogMLStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${scriptsBucket}/cloudformation/glueCatalogML.yml"
      Parameters:
        mlBucket: !Ref mlBucket



  # SNS Topic
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: GlueJobFailureNotifications

  # https://repost.aws/knowledge-center/cloudformation-nested-stacks-values
  StepFunctionStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${scriptsBucket}/cloudformation/stepFunction.yml"
      Parameters:
        LambdaRaw2StagingArn: !GetAtt LambdaStack.Outputs.LambdaRaw2StagingArn
        GlueJobCsv2ParquetArn: !GetAtt GlueJobStack.Outputs.GlueJobCsv2ParquetArn
        GlueJobETLArn: !GetAtt GlueJobStack.Outputs.GlueJobETLArn
        scriptsBucket: !Ref scriptsBucket


  # https://repost.aws/knowledge-center/cloudformation-nested-stacks-values
#  EventBridgeStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: !Sub "https://s3.amazonaws.com/${scriptsBucket}/cloudformation/eventBridge.yml"
#      Parameters:
#        StateMachineArn: !GetAtt StepFunctionStack.Outputs.StateMachineArn


